"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.METEORA_POOL_ID = exports.WISH_WORD = exports.TOKEN_NAME = exports.POOL_ID = exports.TOKEN_MINT = exports.SLIPPAGE = exports.DISTRIBUTE_WALLET_NUM = exports.SELL_INTERVAL_MAX = exports.SELL_INTERVAL_MIN = exports.BUY_INTERVAL_MAX = exports.BUY_INTERVAL_MIN = exports.BUY_LOWER_PERCENT = exports.BUY_UPPER_PERCENT = exports.SWAP_ROUTING = exports.TX_FEE = exports.RPC_WEBSOCKET_ENDPOINT = exports.RPC_ENDPOINT = exports.PRIVATE_KEY = void 0;
const utils_1 = require("../utils");
exports.PRIVATE_KEY = (0, utils_1.retrieveEnvVariable)('PRIVATE_KEY', utils_1.logger);
exports.RPC_ENDPOINT = (0, utils_1.retrieveEnvVariable)('RPC_ENDPOINT', utils_1.logger);
exports.RPC_WEBSOCKET_ENDPOINT = (0, utils_1.retrieveEnvVariable)('RPC_WEBSOCKET_ENDPOINT', utils_1.logger);
exports.TX_FEE = Number((0, utils_1.retrieveEnvVariable)('TX_FEE', utils_1.logger));
exports.SWAP_ROUTING = (0, utils_1.retrieveEnvVariable)('SWAP_ROUTING', utils_1.logger);
exports.BUY_UPPER_PERCENT = Number((0, utils_1.retrieveEnvVariable)('BUY_UPPER_PERCENT', utils_1.logger));
exports.BUY_LOWER_PERCENT = Number((0, utils_1.retrieveEnvVariable)('BUY_LOWER_PERCENT', utils_1.logger));
exports.BUY_INTERVAL_MIN = Number((0, utils_1.retrieveEnvVariable)('BUY_INTERVAL_MIN', utils_1.logger));
exports.BUY_INTERVAL_MAX = Number((0, utils_1.retrieveEnvVariable)('BUY_INTERVAL_MAX', utils_1.logger));
exports.SELL_INTERVAL_MIN = Number((0, utils_1.retrieveEnvVariable)('SELL_INTERVAL_MIN', utils_1.logger));
exports.SELL_INTERVAL_MAX = Number((0, utils_1.retrieveEnvVariable)('SELL_INTERVAL_MAX', utils_1.logger));
exports.DISTRIBUTE_WALLET_NUM = Number((0, utils_1.retrieveEnvVariable)('DISTRIBUTE_WALLET_NUM', utils_1.logger));
exports.SLIPPAGE = Number((0, utils_1.retrieveEnvVariable)('SLIPPAGE', utils_1.logger));
exports.TOKEN_MINT = (0, utils_1.retrieveEnvVariable)('TOKEN_MINT', utils_1.logger);
exports.POOL_ID = (0, utils_1.retrieveEnvVariable)('POOL_ID', utils_1.logger);
exports.TOKEN_NAME = (0, utils_1.retrieveEnvVariable)('TOKEN_NAME', utils_1.logger);
exports.WISH_WORD = (0, utils_1.retrieveEnvVariable)('WISH_WORD', utils_1.logger);
exports.METEORA_POOL_ID = (0, utils_1.retrieveEnvVariable)("METEORA_POOL_ID", utils_1.logger);
